# Site wide configuration

title:            LifeStone
locale:           en_US
baseurl:              "/"
#url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
# markdown:    kramdown
markdown_ext:  markdown,mkd,mkdn,md
remote_theme: cotes2020/chirpy-starter

highlighter: rouge
markdown: kramdown
# kramdown:
    # input: GFM
    # smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # use_coderay: true

  # coderay:
  #   coderay_wrap: div
  #   coderay_line_numbers: nil
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class



# redcarpet:
#   extensions: [fenced_code_blocks]

sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  # - jekyll-toc
  # - jekyll-swfobject

# swfobject:
  # wmode: direct
#   height: 350
#   width: 200

# maruku:
#   use_tex:    false
#   use_divs:   false

# Site owner
owner:
  name: vanCopper
  avatar: van.jpg
  bio: "Try Your Best."
  email: vancopperm@gmail.com
  disqus-shortname: tgerm
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: vanCopper
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
